disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - force_cast
  - empty_count
  - line_length
  - function_parameter_count
  - function_body_length
  - type_body_length
  - type_name
  - force_unwrapping
  - nesting
  - mark
  - identifier_name
  - cyclomatic_complexity
  - file_length
  - shorthand_operator
  - large_tuple
  - generic_type_name
  - notification_center_detachment
  - block_based_kvo
  - multiple_closures_with_trailing_closure
  - switch_case_alignment
  - private_outlet
  - unneeded_break_in_switch
  - compiler_protocol_init
  - for_where
  - empty_enum_arguments
  - protocol_property_accessors_order
  - discarded_notification_center_observer
  - class_delegate_protocol
  - legacy_constant
  - closure_parameter_position
  - private_unit_test
  - unused_closure_parameter
  - weak_delegate
  - closing_brace
  - opening_brace
  - statement_position
  - vertical_parameter_alignment
  - legacy_nsgeometry_functions
  - legacy_constructor
  - legacy_cggeometry_functions
  - force_try
  - void_return
  - valid_ibinspectable
  - unused_optional_binding
  - trailing_comma
  - redundant_void_return
  - redundant_string_enum_value
  - redundant_optional_initialization
  - implicit_getter
  - empty_parentheses_with_trailing_closure
  - empty_parameters
  - redundant_discardable_let
  - comment_spacing
  - unused_setter_value
  - inclusive_language

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Dreamplug/SupportingFiles/Carthage
  - Templates
  # fastlane related
  - fastlane
  - vendor


# opt_in_rules:
#   - conditional_returns_on_newline
#   - fatal_error_message
#   - first_where
#   - closure_spacing
#   - vertical_parameter_alignment_on_call

# configurable rules can be customized from this configuration file

# current warnings
todo:
  severity: warning

#current errors
return_arrow_whitespace:
  severity: error
vertical_whitespace:
  severity: error
trailing_whitespace:
  severity: error
trailing_newline:
  severity: error
leading_whitespace:
  severity: error
colon:
  severity: error
comma:
  severity: error
syntactic_sugar:
  severity: error
trailing_semicolon:
  severity: error
unused_capture_list:
  severity: error
