name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - "**"

jobs:
  lint:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: amannn/action-semantic-pull-request@v4
