
name: Create Release
on:
  push: 
    branches: ["main"]

jobs:
  create_xcframework:
    name: Create XCFramework
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create XCFramework
        run: |
          Scripts/create-xcframework.sh 'SlothCreator'
