
name: Create Release
on:
  push: 
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  create_xcframework:
    name: Create XCFramework
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create XCFramework
        id: framework_builder
        run: |
          path_from_script="bin/mktmp.txt"
          
          # if dir already exits delete it before proceed
          rm -rf "bin"
          
          #create the dir, since we are deleting it in the previous step
          mkdir "bin"
          
          touch $path_from_script
          
          ./Scripts/create-xcframework.sh 'SlothCreator' $path_from_script
          path_to_xcframework=`cat $path_from_script`
          rm -f $path_from_script
          echo ::set-output name=xc_framework::$path_to_xcframework
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ steps.framework_builder.outputs.xc_framework }}
