
name: Create Release
on:
  push: 
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  create_xcframework:
    name: Create XCFramework
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create XCFramework
        id: framework_builder
        run: |
          path_to_xcframework=$(./Scripts/create-xcframework.sh 'SlothCreator')
          echo ::set-output name=xc_framework::$path_to_xcframework
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ steps.framework_builder.outputs.xc_framework }}
