name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        
      - name: Install Swiftlint
        run: |
          set -o pipefail
          export PATH="$PATH:/opt/homebrew/bin"
    
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_fix: true
          swiftlint: true
          swiftlint_args: "--autocorrect --format"
          swiftlint_auto_fix: true
          git_name: ${{ github.event.pusher.name }}
          git_email: ${{ github.event.pusher.email }}
          
