name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show eligible build destinations for SlothCreator
      run: xcodebuild -showdestinations -scheme SlothCreator
    - name: Build and test ( iOS 15.0)
      run: xcodebuild -scheme SlothCreator -destination 'platform=iOS Simulator,id=86727DB6-72F3-47D2-9C08-2E6C8ECDABD7,OS=15.2,name=iPhone 12 Pro'
