name: Test Swift Package Manager Integration

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  on-success:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Test Swift Package Manager Integration
      run: |
        Scripts/test_spm_integration.sh
  on-failure:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Testing SPM integration flow failed'
